version: '3.8'

services:
  podcast-rss:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Persistent volume for data storage
      - podcast_data:/app/data
    environment:
      - NODE_ENV=production
      - DATA_DIR=/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  podcast_data:
    driver: local

